### PR TITLE
[generic/png.c] Add missing error handling

### PR DESCRIPTION
**Pull request by tkoeppe**
The [PNG manual](http://www.libpng.org/pub/png/libpng-1.2.5-manual.html) shows how to clean up after `setjmp(png_jmpbuf(...))`. We were missing the cleanup.

### CODE REVIEW

**Comment by deltheil** [comment]
The other `setjmp` calls (like [this one](https://github.com/torch/image/blob/cde140760fa8b9f03fe3360b3f1a8648cfb9e89b/generic/png.c#L115-L116)) should be handled as well, right? (even though the [current test](https://github.com/torch/image/blob/cde140760fa8b9f03fe3360b3f1a8648cfb9e89b/test/test.lua#L572-L578) will not be enough to cover them)

**Comment by tkoeppe** [comment]
@deltheil: Hm, yes, probably. Done and force-pushed, please have a look.

**Comment by tkoeppe** [comment]
Now that I touched multiple parts of the code, I also uniformized the formatting.

**Comment by deltheil** [comment]
Any reason not to handle the `setjmp` calls from `libpng_(Main_save)` and `libpng_(Main_size)`? It's true that there are a _lot_ of code paths where errors occur, and most of them do not release resources properly right now... (the file handle, the PNG struct, etc)

IMHO a `goto` approach for error handling would be of great help, like replacing every call to `luaL_error(L, "foo %s", "bar")` by `lua_pushfstring(L, "foo %s", "bar"); goto err;` and use a final `err` section like:

```C
err:
  /* release all resources here, e.g. */
  if (fp) fclose(fp);
  /* ... */

  return lua_error(L);
```

**Comment by tkoeppe** [comment]
@deltheil: The only reason for why I do and don't do any one thing is this: I didn't write the code (otherwise there'd be nothing inconsistent or missing :-) ), and I only spot problems when they surface in tests.

If there's anything else you'd like done to this code, you can either point me to it (within scope of a single commit), or perform a separate, systematic code review of this package later (that's probably a better idea in the long run). In particular, wasn't comfortable installing a `goto`-based error handling system here, because to me that would be part of a fundamental design idiom that I would want broader project lead support and guidance on, and I wouldn't want to just randomly use that in one place. A lot of the Torch code suffers from similar problems of not handling multiple exits well, and it would benefit from a general code design guideline, but that's not something I'd want to start in an ad-hoc way like this.

All I want to achieve here is fix a memory leak in a common code path (bad file format), and I'm more willing to ignore the more obscure code paths (like no more file descriptors, out of memory). In other words, code paths that most likely lead to whole-process termination aren't quite as interesting in leaf libraries like this as those arising from regular operation.

**Comment by deltheil** [comment]
Right, makes sense. I had similar concerns while improving error reporting (like in #100).

> All I want to achieve here is fix a memory leak in a common code path

Allright. So no more remarks :)

**Comment by tkoeppe** [comment]
> Alright. So no more remarks :)

Hehe - to be clear, I just want to avoid scope creep for this change, so that it doesn't end up stranded forever because it doesn't achieve perfection. I'm totally in favour of a systematic review and overhaul of the existing codebase.

**Comment by tkoeppe** [comment]
@soumith: could you please review this PR?

**Comment by soumith** [comment]
Looks good to me! Thanks @tkoeppe

**Pull request merged**
