### PR TITLE
Restore tests lost in commit 03e65a.

### PR DESCRIPTION
**Pull request by jagapiou**
Some of the newer tests in test_scale got lost in the reconciliation of the
tests.

* Restored lost test_scale.lua tests
* Ensured that tests still run (with a warning) if graphicsmagick is missing.

### CODE REVIEW

**Comment by jagapiou** [comment]
@albanD could you please check whether any other tests were introduced after your last sync?

**Comment by albanD** [comment]
@jagapiou thanks a lot for the test_scale. I am really sorry (I though this would have been caught in the rebase). I double checked, no other test got forgotten.

**Comment by jagapiou** [comment]
No problem, @albanD. Thanks.

**Comment by albanD** [comment]
@jagapiou don't you think your version of `assertTensorEq ` should be used by all tests that call `tester:assertTensorEq ` ?

**Comment by deltheil** [comment]
:+1: for soft requirement on graphicsmagick (`test.CompareLoadAndDecompress()`)

**Comment by jagapiou** [comment]
@albanD actually, I've pushed it down to just be assertByteTensorEq and to use tester:assertTensorEq() after conversion to double. Less reinvention that way.

**Comment by albanD** [comment]
@jagapiou looks good to me.

**Pull request merged**
