### PR TITLE
Added docs for decompressJPG.  Added compressJPG function.

### PR DESCRIPTION
**Pull request by jonathantompson**
Also added documentation for it and a unit test.

### CODE REVIEW

**Comment by jonathantompson** [comment]
Considering that image.save is a heavily used function, I think this PR needs a code-review.  I had another scan through the code just now, but it needs another set of eyes.

**Comment by soumith** [comment]
it looks good to me overall. will let it sit for a day anyways. very useful function!

**Comment by jonathantompson** [comment]
Cool.  Thanks for looking it over.

Hopefully, while sitting there for a few days, this PR turns into something that "solves AI"...  It would make our lives easier.

**Comment by deltheil** [comment]
:+1:

I was looking for an equivalent to `local blob = img:toString(quality)` with [graphicsmagick](https://github.com/clementfarabet/graphicsmagick). And this is now possible with:

```Lua
local blob = image.compressJPG(img, quality):storage():string()
```

That said: I have a compiler warning with Clang (`-Wpointer-sign`). To get rid of it:

```diff
diff --git a/generic/jpeg.c b/generic/jpeg.c
index 2cc4a57..8ab5ba0 100755
--- a/generic/jpeg.c
+++ b/generic/jpeg.c
@@ -446,9 +446,9 @@ int libjpeg_(Main_save)(lua_State *L) {
   }
 
   if (save_to_file == 0) {
-    
-    THByteTensor_resize1d(tensor_dest, inmem_size);  /* will fail if it's not a Byte Tensor */ 
-    char* tensor_dest_data = THByteTensor_data(tensor_dest); 
+
+    THByteTensor_resize1d(tensor_dest, inmem_size);  /* will fail if it's not a Byte Tensor */
+    unsigned char* tensor_dest_data = THByteTensor_data(tensor_dest);
     memcpy(tensor_dest_data, inmem, inmem_size);
     free(inmem);
   }
```

**Comment by jonathantompson** [comment]
Thanks @deltheil!  I changed the char to unsigned char and force pushed the commit.

Sorry about that.  I'm usually pretty pedantic when it comes to compiler warnings, but I must have missed that one.

**Comment by soumith** [comment]
combining with tds.hash(), it becomes a perfect format to store large datasets in-memory.
https://github.com/torch/tds

**Comment by jonathantompson** [comment]
Yeah, I was thinking though we might want a decompressPNG / compressPNG function.  For some applications I can imagine that even JPEG quality 100 isn't enough (ie scientific applications).

**Comment by soumith** [comment]
thanks jono

**Pull request merged**
